### ISSUE TITLE
参考proxysql，在admin接口实现kill命令

### ISSUE THREAD

**Issue by wangbin579** [Lede-Inc/cetus#116]
需要处理好不同进程之间产生thread id的问题，不能重复，否则admin去处理的时候不知道杀哪一个.

同时admin接口支持show connectionlist where pid = xxxx

**Comment by lazio579** [comment]
目前实行方式是kill query tid，通过tid来找到session的前后端连接，并强行关闭这些连接，这个与传统的kill query tid方式不同
