### ISSUE TITLE
select sum(field1)/10000 结果和 sum(field1/10000) 结果不一样

### ISSUE THREAD

**Issue by HashZhang** [Lede-Inc/cetus#12]
如题，在使用过程中，发现select sum(field1)/10000 结果和 sum(field1/10000) 结果不一样

**Comment by HashZhang** [comment]
如果需要例子，请popo联系我，zhanghaoxin

**Comment by etern** [comment]
多个分库的聚合函数到cetus会再聚合，sum(field)/1000把聚合函数嵌入算术表达式，多种聚合函数加减乘除处理比较复杂，先禁用，给用户提示。用户可以使用sum(field/1000)来完成查询。
