### ISSUE TITLE
(select emp_no,dept_no from employees_mix.dept_manager limit 2 ) union all (select emp_no,dept_no from employees_mix.dept_emp limit 2)

### ISSUE THREAD

**Issue by lazio579** [Lede-Inc/cetus#151]
解析器还不支持这种语法，需要解决

**Comment by wangbin579** [comment]
目前可以采用类似方案：
在shard配置文件设置：
enable-sql-special-processed=true

具体使用的时候：
/*#group=data1*/ (select emp_no,dept_no from employees_mix.dept_manager limit 2 ) union all (select emp_no,dept_no from employees_mix.dept_emp limit 2);

在不支持sql的前面加上/*#group=data1*/ 注释，显式指定后端路由，这样cetus就不会去解析sql找路由

具体注释参考github文档
