### ISSUE TITLE
使用Quartz出现异常 Couldn't acquire next trigger: SET of SQL_SELECT_LIMIT is not supported

### ISSUE THREAD

**Issue by zeyuphoenix** [Lede-Inc/cetus#168]
部署后简单使用没问题,加入项目后,因为项目使用了quartz框架,出现 Couldn't acquire next trigger: SET of SQL_SELECT_LIMIT is not supported 异常, 请问这个有办法通过配置解决吗？

**Comment by zeyuphoenix** [comment]
谢谢
![image](https://user-images.githubusercontent.com/3367482/50573031-0ef4e080-0e07-11e9-8638-028c2e534190.png)
加入了这个之后没异常了应该可以了

**Comment by zch513430014** [comment]
我在使用阿里云 datawork数据同步也出现这个问题了
