### ISSUE TITLE
针对分库分表模式下数据库连接的异常

### ISSUE THREAD

**Issue by aeoluswing** [Lede-Inc/cetus#169]
sharding版本配置完后，根据sharding规则导入了数据，确认数据分片成功，但是连接数据库时一直有问题。假设proxy-address为6001端口，管理口为7001
首先，采用workbench连接数据库，测试发现无法连接，异常提示为`SET TRANSACTION not supported`.
其次，jmeter上采用jdbc驱动(com.mysql.jdbc.Driver)连接数据库(驱动版本大于5.1.21)，测试发现无法连接，异常提示为`Response message: java.sql.SQLException: Cannot create PoolableConnectionFactory (SET of character_set_results is not supported)
`，查看源码，发现这是结果字符集设置问题，检查配置文件，在variables.json中配置了character_set_results的允许值为"latin1","ascii","gb2312","gbk","utf8","utf8mb4","binary","big5"，但是日志中显示`(message) plugins/shard/shard-plugin.c:663 SQL unsupported: SET of character_set_results is not supported. while parsing: SET character_set_results = NULL,`，可以看出，shard插件有一个将结果字符集设置为null的动作，可能因此不被cetus支持？
以下为shard.conf配置:
```
[cetus]
verbose-shutdown=true
daemon=true
basedir=/home/user/cetus_install
conf-dir=/home/user/cetus_install/conf/
pid-file=/home/user/cetus_install/cetus6001.pid
plugin-dir=lib/cetus/plugins
plugins=shard,admin
log-level=debug
log-file=/data/cetus/cetus_6001.log
log-xa-file=/data/cetus/logs6001/xa.log
max-open-files=65536
default-charset=utf8
default-username=root
default-db=et_ci
ifname=eth0
default-pool-size=10
max-pool-size=400
worker-processes=6
worker-id=323
ssl=false
slave-delay-down=5.000000
slave-delay-recover=1.000000
long-query-time=500
enable-client-found-rows=true
reduce-connections=true
sql-log-bufsize=10485760
sql-log-switch=REALTIME
sql-log-prefix=cetus
sql-log-path=/home/user/cetus_install/logs
sql-log-maxsize=1024
sql-log-mode=ALL
proxy-address=0.0.0.0:6001
proxy-backend-addresses=xxx@data1,xxx:3306@data2,xxx:3306@data3
allow-nested-subquery=false
admin-address=0.0.0.0:7001
admin-username=admin
admin-password=admin
```
通过mysql直接连接6001和7001口都可以正常访问(账号密码已在user.json中配置)，则应用如何连接cetus？无法直接通过proxy-address访问吗？

**Comment by aeoluswing** [comment]
在配置文件variables.json中配置
```
{
    "name": "character_set_results",
    "type": "string",
    "allowed_values": ["latin1","ascii","gb2312","gbk","utf8","utf8mb4","binary","big5","NULL"],
    "silent_values": ["*"]
}
```
可以解决jdbc驱动连接proxy报`set of character_set_results not supported`的异常

**Comment by Hokkaitao** [comment]
1 mysql workbench 连接MySQL的时候，会发送：SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ。 该SQL Cetus目前不支持，因此workbench 直连Cetus会报错。

应用程序中一般不会有set session之类的SQL，因此应用程序使用Cetus应该没有问题。建议可以:a workbench 是否有参数控制 禁止 发送该 SQL； b 使用其他工具代替workbench，比如navcat。

2 SET character_set_results = NULL 报错。该SQL Cetus也不支持。不过这种 set key=value形式的不支持的SQL，Cetus可以通过配置静默变量来屏蔽报错。在variables.json中配置的方法如下：
## cat variables.json
{
    "variables": [
        {
            "name": "character_set_results",
            "type": "string",
            "allowed_values": ["*"],
            "silent_values": ["*"]
        }
    ]
}
