### ISSUE TITLE
libmysql-chassis-proxy.so: undefined reference to `g_list_free_full'

### ISSUE THREAD

**Issue by yidazhi** [Lede-Inc/cetus#17]
[root@mysql8 build]# make install
[  3%] Built target mysql-chassis-glibext
[  6%] Built target mysql-chassis-timing
[ 30%] Built target mysql-chassis
[ 33%] Built target lemon
[ 51%] Built target sqlparser
[ 90%] Built target mysql-chassis-proxy
[ 91%] Linking C executable cetus
libmysql-chassis-proxy.so: undefined reference to `g_list_free_full'
collect2: ld returned 1 exit status
make[2]: *** [src/cetus] Error 1
make[1]: *** [src/CMakeFiles/cetus.dir/all] Error 2
执行make install报错libmysql-chassis-proxy.so: undefined reference to `g_list_free_full'，请问大神们，我这个是缺包还是啥？查了半天没啥结果

**Comment by lazio579** [comment]
glib库可能太老了，需要2.28+才能编译

**Comment by lazio579** [comment]
后续我们会加上glib版本的检测

**Comment by etern** [comment]
76d5be2

**Comment by yidazhi** [comment]
@lazio579 好的，我是2.26，十分感谢
