### ISSUE TITLE
多进程实现思路

### ISSUE THREAD

**Issue by lazio579** [Lede-Inc/cetus#34]
利用内核3.9+的SO_REUSEPORT机制，多个work进程共同监听一个端口，而多进程如果需要通信，则可以参考nginx socket pair来通信，确保多进程之间没有锁访问

admin用单独的进程来做，可以从共享内存里面获取相关信息

**Comment by zag2017** [comment]
SO_REUSEPORT 单进程+多线程模式也可以.

**Comment by wangbin579** [comment]
已经初步在multi-process分支实现
