### ISSUE TITLE
cetus自动识别MySQL主从

### ISSUE THREAD

**Issue by lazio579** [Lede-Inc/cetus#85]

**Comment by bayannur** [comment]
两种需要自动识别MySQL主从角色的场景：
1、MGR写节点变更。开启cetus支持mgr模式，cetus会间隔检测写节点，发现写节点变更后自动更新cetus中MySQL节点的新主从角色和存活状态。
2、一主多从。cetus项目组改写的mha软件，在主从关系变化，或则主库down机情况下，会提升新的主库，并且通知cetus MySQL节点的新主从角色和存活状态。
综上，cetus暂时不需要开发自动识别MySQL主从的功能。
